exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "Credits.md"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

title: "Remote Çalışmak"
subtitle: "Remote çalışmak ile ilgili bilmek istediğiniz her şey"
markdown: kramdown
